# Generated by Django 4.0.4 on 2022-11-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='auto_token',
            new_name='auth_token',
        ),
    ]
