# Generated by Django 4.0.4 on 2022-11-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contractor_studentprofile_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_stud_roll', models.IntegerField()),
                ('sm_name', models.CharField(max_length=70)),
                ('sm_dob', models.DateField()),
                ('sm_date', models.DateField()),
                ('sm_father_name', models.CharField(max_length=60)),
                ('sm_mother_name', models.CharField(max_length=60)),
                ('subject_1', models.IntegerField()),
                ('subject_2', models.IntegerField()),
                ('subject_3', models.IntegerField()),
                ('subject_4', models.IntegerField()),
                ('subject_5', models.IntegerField()),
                ('subject_6', models.IntegerField()),
            ],
        ),
    ]
