# Generated by Django 4.0.4 on 2022-11-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_studentmarksheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmarksheet',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentmarksheet',
            name='sm_stud_roll',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
